version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "443:8080"
      - "80:80"
    volumes:
      - ./secret_guide/static:/srv/www/secret_guide/static
      - ./secret_guide/media:/srv/www/secret_guide/media
      - ./secret_guide/logs:/srv/www/secret_guide/logs
      - ./docker/nginx:/etc/nginx/conf.d
      # - /etc/ssl/:/etc/ssl
    depends_on:
      - python

  python:
    restart: always
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./secret_guide:/srv/www/secret_guide
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    command: gunicorn --log-level DEBUG -c gunicorn.py secret_guide.wsgi
