# Generated by Django 4.0.5 on 2022-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_quest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconswhen',
            name='file',
            field=models.FileField(default=1, upload_to='', verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iconswhy',
            name='file',
            field=models.FileField(default=1, upload_to='', verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='photo',
            field=models.ManyToManyField(to='quests.photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reviews',
            field=models.ManyToManyField(to='quests.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='video',
            field=models.ManyToManyField(to='quests.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='when_it_need',
            field=models.ManyToManyField(to='quests.iconswhen', verbose_name='Иконки когда'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='why_it_need',
            field=models.ManyToManyField(to='quests.iconswhy', verbose_name='Иконки почему'),
        ),
    ]
