# Generated by Django 4.0.6 on 2022-07-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_quest_name_rus_alter_quest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='main_photo',
            field=models.FileField(default='/', upload_to='main_photo', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iconswhen',
            name='file',
            field=models.FileField(upload_to='icons_when', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='iconswhy',
            name='file',
            field=models.FileField(upload_to='icons_why', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='photo', verbose_name='Файл с фото'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.FileField(upload_to='reviews', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video', verbose_name='Файл с видео'),
        ),
    ]
