# Generated by Django 4.0.5 on 2022-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_rename_what_waits_yo_quest_what_waits_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
