# Generated by Django 4.0.5 on 2022-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_iconswhen_file_iconswhy_file_alter_quest_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name_rus',
            field=models.CharField(default=123, max_length=255, verbose_name='Название квеста рус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название квеста англ'),
        ),
    ]
