# Generated by Django 3.2.3 on 2022-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_quest_main_photo_review_rate_alter_iconswhen_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='quests.Photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='quests.Review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='quests.Video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='when_it_need',
            field=models.ManyToManyField(blank=True, null=True, to='quests.IconsWhen', verbose_name='Иконки когда'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='why_it_need',
            field=models.ManyToManyField(blank=True, null=True, to='quests.IconsWhy', verbose_name='Иконки почему'),
        ),
    ]
