# Generated by Django 4.0.5 on 2022-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kstati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=100, verbose_name='Название квеста')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('text', models.TextField(verbose_name='Текст выплывающего окна')),
                ('button', models.BooleanField(verbose_name='Добавить кнопку')),
                ('button_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название кнопки')),
                ('button_on_click', models.TextField(blank=True, null=True, verbose_name='Действие на кнопку')),
            ],
            options={
                'verbose_name': 'Кстати',
                'verbose_name_plural': 'Кстати',
            },
        ),
    ]
